#include "bmfile.h"

#pragma warning(disable:4305)

namespace bvh {
	namespace features {
		namespace mapping {
			namespace bmfile {

				const char* CONST_ExternalTextureList[] = {
					"atari.avi",
					"atari.bmp",
					"Ball_LightningSphere1.bmp",
					"Ball_LightningSphere2.bmp",
					"Ball_LightningSphere3.bmp",
					"Ball_Paper.bmp",
					"Ball_Stone.bmp",
					"Ball_Wood.bmp",
					"Brick.bmp",
					"Button01_deselect.tga",
					"Button01_select.tga",
					"Button01_special.tga",
					"Column_beige.bmp",
					"Column_beige_fade.tga",
					"Column_blue.bmp",
					"Cursor.tga",
					"Dome.bmp",
					"DomeEnvironment.bmp",
					"DomeShadow.tga",
					"ExtraBall.bmp",
					"ExtraParticle.bmp",
					"E_Holzbeschlag.bmp",
					"FloorGlow.bmp",
					"Floor_Side.bmp",
					"Floor_Top_Border.bmp",
					"Floor_Top_Borderless.bmp",
					"Floor_Top_Checkpoint.bmp",
					"Floor_Top_Flat.bmp",
					"Floor_Top_Profil.bmp",
					"Floor_Top_ProfilFlat.bmp",
					"Font_1.tga",
					"Gravitylogo_intro.bmp",
					"HardShadow.bmp",
					"Laterne_Glas.bmp",
					"Laterne_Schatten.tga",
					"Laterne_Verlauf.tga",
					"Logo.bmp",
					"Metal_stained.bmp",
					"Misc_Ufo.bmp",
					"Misc_UFO_Flash.bmp",
					"Modul03_Floor.bmp",
					"Modul03_Wall.bmp",
					"Modul11_13_Wood.bmp",
					"Modul11_Wood.bmp",
					"Modul15.bmp",
					"Modul16.bmp",
					"Modul18.bmp",
					"Modul18_Gitter.tga",
					"Modul30_d_Seiten.bmp",
					"Particle_Flames.bmp",
					"Particle_Smoke.bmp",
					"PE_Bal_balloons.bmp",
					"PE_Bal_platform.bmp",
					"PE_Ufo_env.bmp",
					"Pfeil.tga",
					"P_Extra_Life_Oil.bmp",
					"P_Extra_Life_Particle.bmp",
					"P_Extra_Life_Shadow.bmp",
					"Rail_Environment.bmp",
					"sandsack.bmp",
					"SkyLayer.bmp",
					"Sky_Vortex.bmp",
					"Stick_Bottom.tga",
					"Stick_Stripes.bmp",
					"Target.bmp",
					"Tower_Roof.bmp",
					"Trafo_Environment.bmp",
					"Trafo_FlashField.bmp",
					"Trafo_Shadow_Big.tga",
					"Tut_Pfeil01.tga",
					"Tut_Pfeil_Hoch.tga",
					"Wolken_intro.tga",
					"Wood_Metal.bmp",
					"Wood_MetalStripes.bmp",
					"Wood_Misc.bmp",
					"Wood_Nailed.bmp",
					"Wood_Old.bmp",
					"Wood_Panel.bmp",
					"Wood_Plain.bmp",
					"Wood_Plain2.bmp",
					"Wood_Raft.bmp"
				};
				const uint32_t CONST_ExternalTextureList_Length = sizeof(CONST_ExternalTextureList) / sizeof(char*);	//following list's length. not to change this when the list is changed

				const char* CONST_ExternalComponent[] = {
					"P_Extra_Life",
					"P_Extra_Point",
					"P_Trafo_Paper",
					"P_Trafo_Stone",
					"P_Trafo_Wood",
					"P_Ball_Paper",
					"P_Ball_Stone",
					"P_Ball_Wood",
					"P_Box",
					"P_Dome",
					"P_Modul_01",
					"P_Modul_03",
					"P_Modul_08",
					"P_Modul_17",
					"P_Modul_18",
					"P_Modul_19",
					"P_Modul_25",
					"P_Modul_26",
					"P_Modul_29",
					"P_Modul_30",
					"P_Modul_34",
					"P_Modul_37",
					"P_Modul_41",
					"PC_TwoFlames",
					"PE_Balloon",
					"PR_Resetpoint",
					"PS_FourFlames"
				};
				const uint32_t CONST_ExternalComponent_Length = sizeof(CONST_ExternalComponent) / sizeof(char*);	//following list's length. not to change this when the list is changed

			}
		}
	}
}